// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
    // We also try to prevent mixing versions of shared uniffi header structs.
    // If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V4
    #ifndef UNIFFI_SHARED_HEADER_V4
        #error Combining helper code from multiple versions of uniffi is not supported
    #endif // ndef UNIFFI_SHARED_HEADER_V4
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V4
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️

typedef struct RustBuffer
{
    uint64_t capacity;
    uint64_t len;
    uint8_t *_Nullable data;
} RustBuffer;

typedef struct ForeignBytes
{
    int32_t len;
    const uint8_t *_Nullable data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
    int8_t code;
    RustBuffer errorBuf;
} RustCallStatus;

// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️
#endif // def UNIFFI_SHARED_H
#ifndef UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
#define UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
typedef void (*UniffiRustFutureContinuationCallback)(uint64_t, int8_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK
typedef void (*UniffiForeignFutureDroppedCallback)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
typedef void (*UniffiCallbackInterfaceFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_CLONE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_CLONE
typedef uint64_t (*UniffiCallbackInterfaceClone)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK_STRUCT
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK_STRUCT
typedef struct UniffiForeignFutureDroppedCallbackStruct {
    uint64_t handle;
    UniffiForeignFutureDroppedCallback _Nonnull free;
} UniffiForeignFutureDroppedCallbackStruct;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U8
typedef struct UniffiForeignFutureResultU8 {
    uint8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
typedef void (*UniffiForeignFutureCompleteU8)(uint64_t, UniffiForeignFutureResultU8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I8
typedef struct UniffiForeignFutureResultI8 {
    int8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
typedef void (*UniffiForeignFutureCompleteI8)(uint64_t, UniffiForeignFutureResultI8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U16
typedef struct UniffiForeignFutureResultU16 {
    uint16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
typedef void (*UniffiForeignFutureCompleteU16)(uint64_t, UniffiForeignFutureResultU16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I16
typedef struct UniffiForeignFutureResultI16 {
    int16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
typedef void (*UniffiForeignFutureCompleteI16)(uint64_t, UniffiForeignFutureResultI16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U32
typedef struct UniffiForeignFutureResultU32 {
    uint32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
typedef void (*UniffiForeignFutureCompleteU32)(uint64_t, UniffiForeignFutureResultU32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I32
typedef struct UniffiForeignFutureResultI32 {
    int32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
typedef void (*UniffiForeignFutureCompleteI32)(uint64_t, UniffiForeignFutureResultI32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U64
typedef struct UniffiForeignFutureResultU64 {
    uint64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
typedef void (*UniffiForeignFutureCompleteU64)(uint64_t, UniffiForeignFutureResultU64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I64
typedef struct UniffiForeignFutureResultI64 {
    int64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
typedef void (*UniffiForeignFutureCompleteI64)(uint64_t, UniffiForeignFutureResultI64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F32
typedef struct UniffiForeignFutureResultF32 {
    float returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultF32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
typedef void (*UniffiForeignFutureCompleteF32)(uint64_t, UniffiForeignFutureResultF32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F64
typedef struct UniffiForeignFutureResultF64 {
    double returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultF64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
typedef void (*UniffiForeignFutureCompleteF64)(uint64_t, UniffiForeignFutureResultF64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_RUST_BUFFER
typedef struct UniffiForeignFutureResultRustBuffer {
    RustBuffer returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultRustBuffer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
typedef void (*UniffiForeignFutureCompleteRustBuffer)(uint64_t, UniffiForeignFutureResultRustBuffer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_VOID
typedef struct UniffiForeignFutureResultVoid {
    RustCallStatus callStatus;
} UniffiForeignFutureResultVoid;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
typedef void (*UniffiForeignFutureCompleteVoid)(uint64_t, UniffiForeignFutureResultVoid
    );

#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MOB_FN_CLONE_CLIENT
#define UNIFFI_FFIDEF_UNIFFI_MOB_FN_CLONE_CLIENT
uint64_t uniffi_mob_fn_clone_client(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MOB_FN_FREE_CLIENT
#define UNIFFI_FFIDEF_UNIFFI_MOB_FN_FREE_CLIENT
void uniffi_mob_fn_free_client(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MOB_FN_CONSTRUCTOR_CLIENT_NEW
#define UNIFFI_FFIDEF_UNIFFI_MOB_FN_CONSTRUCTOR_CLIENT_NEW
uint64_t uniffi_mob_fn_constructor_client_new(RustBuffer config, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MOB_FN_CONSTRUCTOR_CLIENT_NEW_WITH_SIGNER
#define UNIFFI_FFIDEF_UNIFFI_MOB_FN_CONSTRUCTOR_CLIENT_NEW_WITH_SIGNER
uint64_t uniffi_mob_fn_constructor_client_new_with_signer(RustBuffer config, uint64_t signer, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MOB_FN_METHOD_CLIENT_ATTACH_SIGNER
#define UNIFFI_FFIDEF_UNIFFI_MOB_FN_METHOD_CLIENT_ATTACH_SIGNER
void uniffi_mob_fn_method_client_attach_signer(uint64_t ptr, uint64_t _signer, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MOB_FN_METHOD_CLIENT_EXECUTE_CONTRACT
#define UNIFFI_FFIDEF_UNIFFI_MOB_FN_METHOD_CLIENT_EXECUTE_CONTRACT
RustBuffer uniffi_mob_fn_method_client_execute_contract(uint64_t ptr, RustBuffer contract_address, RustBuffer msg, RustBuffer funds, RustBuffer granter, RustBuffer fee_granter, RustBuffer memo, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MOB_FN_METHOD_CLIENT_GET_ACCOUNT
#define UNIFFI_FFIDEF_UNIFFI_MOB_FN_METHOD_CLIENT_GET_ACCOUNT
RustBuffer uniffi_mob_fn_method_client_get_account(uint64_t ptr, RustBuffer address, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MOB_FN_METHOD_CLIENT_GET_ALL_BALANCES
#define UNIFFI_FFIDEF_UNIFFI_MOB_FN_METHOD_CLIENT_GET_ALL_BALANCES
RustBuffer uniffi_mob_fn_method_client_get_all_balances(uint64_t ptr, RustBuffer address, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MOB_FN_METHOD_CLIENT_GET_BALANCE
#define UNIFFI_FFIDEF_UNIFFI_MOB_FN_METHOD_CLIENT_GET_BALANCE
RustBuffer uniffi_mob_fn_method_client_get_balance(uint64_t ptr, RustBuffer address, RustBuffer denom, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MOB_FN_METHOD_CLIENT_GET_CHAIN_ID
#define UNIFFI_FFIDEF_UNIFFI_MOB_FN_METHOD_CLIENT_GET_CHAIN_ID
RustBuffer uniffi_mob_fn_method_client_get_chain_id(uint64_t ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MOB_FN_METHOD_CLIENT_GET_HEIGHT
#define UNIFFI_FFIDEF_UNIFFI_MOB_FN_METHOD_CLIENT_GET_HEIGHT
uint64_t uniffi_mob_fn_method_client_get_height(uint64_t ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MOB_FN_METHOD_CLIENT_GET_TX
#define UNIFFI_FFIDEF_UNIFFI_MOB_FN_METHOD_CLIENT_GET_TX
RustBuffer uniffi_mob_fn_method_client_get_tx(uint64_t ptr, RustBuffer hash, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MOB_FN_METHOD_CLIENT_IS_SYNCED
#define UNIFFI_FFIDEF_UNIFFI_MOB_FN_METHOD_CLIENT_IS_SYNCED
int8_t uniffi_mob_fn_method_client_is_synced(uint64_t ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MOB_FN_METHOD_CLIENT_SEND
#define UNIFFI_FFIDEF_UNIFFI_MOB_FN_METHOD_CLIENT_SEND
RustBuffer uniffi_mob_fn_method_client_send(uint64_t ptr, RustBuffer to_address, RustBuffer amount, RustBuffer granter, RustBuffer fee_granter, RustBuffer memo, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MOB_FN_CLONE_SIGNER
#define UNIFFI_FFIDEF_UNIFFI_MOB_FN_CLONE_SIGNER
uint64_t uniffi_mob_fn_clone_signer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MOB_FN_FREE_SIGNER
#define UNIFFI_FFIDEF_UNIFFI_MOB_FN_FREE_SIGNER
void uniffi_mob_fn_free_signer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MOB_FN_CONSTRUCTOR_SIGNER_FROM_MNEMONIC
#define UNIFFI_FFIDEF_UNIFFI_MOB_FN_CONSTRUCTOR_SIGNER_FROM_MNEMONIC
uint64_t uniffi_mob_fn_constructor_signer_from_mnemonic(RustBuffer mnemonic, RustBuffer address_prefix, RustBuffer derivation_path, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MOB_FN_METHOD_SIGNER_ADDRESS
#define UNIFFI_FFIDEF_UNIFFI_MOB_FN_METHOD_SIGNER_ADDRESS
RustBuffer uniffi_mob_fn_method_signer_address(uint64_t ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MOB_FN_METHOD_SIGNER_ADDRESS_PREFIX
#define UNIFFI_FFIDEF_UNIFFI_MOB_FN_METHOD_SIGNER_ADDRESS_PREFIX
RustBuffer uniffi_mob_fn_method_signer_address_prefix(uint64_t ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MOB_FN_METHOD_SIGNER_PUBLIC_KEY_HEX
#define UNIFFI_FFIDEF_UNIFFI_MOB_FN_METHOD_SIGNER_PUBLIC_KEY_HEX
RustBuffer uniffi_mob_fn_method_signer_public_key_hex(uint64_t ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MOB_FN_METHOD_SIGNER_SIGN_BYTES
#define UNIFFI_FFIDEF_UNIFFI_MOB_FN_METHOD_SIGNER_SIGN_BYTES
RustBuffer uniffi_mob_fn_method_signer_sign_bytes(uint64_t ptr, RustBuffer message, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MOB_RUSTBUFFER_ALLOC
#define UNIFFI_FFIDEF_FFI_MOB_RUSTBUFFER_ALLOC
RustBuffer ffi_mob_rustbuffer_alloc(uint64_t size, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MOB_RUSTBUFFER_FROM_BYTES
#define UNIFFI_FFIDEF_FFI_MOB_RUSTBUFFER_FROM_BYTES
RustBuffer ffi_mob_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MOB_RUSTBUFFER_FREE
#define UNIFFI_FFIDEF_FFI_MOB_RUSTBUFFER_FREE
void ffi_mob_rustbuffer_free(RustBuffer buf, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MOB_RUSTBUFFER_RESERVE
#define UNIFFI_FFIDEF_FFI_MOB_RUSTBUFFER_RESERVE
RustBuffer ffi_mob_rustbuffer_reserve(RustBuffer buf, uint64_t additional, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_POLL_U8
#define UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_POLL_U8
void ffi_mob_rust_future_poll_u8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_CANCEL_U8
#define UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_CANCEL_U8
void ffi_mob_rust_future_cancel_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_FREE_U8
#define UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_FREE_U8
void ffi_mob_rust_future_free_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_COMPLETE_U8
uint8_t ffi_mob_rust_future_complete_u8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_POLL_I8
#define UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_POLL_I8
void ffi_mob_rust_future_poll_i8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_CANCEL_I8
#define UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_CANCEL_I8
void ffi_mob_rust_future_cancel_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_FREE_I8
#define UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_FREE_I8
void ffi_mob_rust_future_free_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_COMPLETE_I8
int8_t ffi_mob_rust_future_complete_i8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_POLL_U16
#define UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_POLL_U16
void ffi_mob_rust_future_poll_u16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_CANCEL_U16
#define UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_CANCEL_U16
void ffi_mob_rust_future_cancel_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_FREE_U16
#define UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_FREE_U16
void ffi_mob_rust_future_free_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_COMPLETE_U16
uint16_t ffi_mob_rust_future_complete_u16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_POLL_I16
#define UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_POLL_I16
void ffi_mob_rust_future_poll_i16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_CANCEL_I16
#define UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_CANCEL_I16
void ffi_mob_rust_future_cancel_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_FREE_I16
#define UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_FREE_I16
void ffi_mob_rust_future_free_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_COMPLETE_I16
int16_t ffi_mob_rust_future_complete_i16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_POLL_U32
#define UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_POLL_U32
void ffi_mob_rust_future_poll_u32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_CANCEL_U32
#define UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_CANCEL_U32
void ffi_mob_rust_future_cancel_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_FREE_U32
#define UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_FREE_U32
void ffi_mob_rust_future_free_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_COMPLETE_U32
uint32_t ffi_mob_rust_future_complete_u32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_POLL_I32
#define UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_POLL_I32
void ffi_mob_rust_future_poll_i32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_CANCEL_I32
#define UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_CANCEL_I32
void ffi_mob_rust_future_cancel_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_FREE_I32
#define UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_FREE_I32
void ffi_mob_rust_future_free_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_COMPLETE_I32
int32_t ffi_mob_rust_future_complete_i32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_POLL_U64
#define UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_POLL_U64
void ffi_mob_rust_future_poll_u64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_CANCEL_U64
#define UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_CANCEL_U64
void ffi_mob_rust_future_cancel_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_FREE_U64
#define UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_FREE_U64
void ffi_mob_rust_future_free_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_COMPLETE_U64
uint64_t ffi_mob_rust_future_complete_u64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_POLL_I64
#define UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_POLL_I64
void ffi_mob_rust_future_poll_i64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_CANCEL_I64
#define UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_CANCEL_I64
void ffi_mob_rust_future_cancel_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_FREE_I64
#define UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_FREE_I64
void ffi_mob_rust_future_free_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_COMPLETE_I64
int64_t ffi_mob_rust_future_complete_i64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_POLL_F32
#define UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_POLL_F32
void ffi_mob_rust_future_poll_f32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_CANCEL_F32
#define UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_CANCEL_F32
void ffi_mob_rust_future_cancel_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_FREE_F32
#define UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_FREE_F32
void ffi_mob_rust_future_free_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_COMPLETE_F32
float ffi_mob_rust_future_complete_f32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_POLL_F64
#define UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_POLL_F64
void ffi_mob_rust_future_poll_f64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_CANCEL_F64
#define UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_CANCEL_F64
void ffi_mob_rust_future_cancel_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_FREE_F64
#define UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_FREE_F64
void ffi_mob_rust_future_free_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_COMPLETE_F64
double ffi_mob_rust_future_complete_f64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_POLL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_POLL_RUST_BUFFER
void ffi_mob_rust_future_poll_rust_buffer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_CANCEL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_CANCEL_RUST_BUFFER
void ffi_mob_rust_future_cancel_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_FREE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_FREE_RUST_BUFFER
void ffi_mob_rust_future_free_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_COMPLETE_RUST_BUFFER
RustBuffer ffi_mob_rust_future_complete_rust_buffer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_POLL_VOID
#define UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_POLL_VOID
void ffi_mob_rust_future_poll_void(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_CANCEL_VOID
#define UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_CANCEL_VOID
void ffi_mob_rust_future_cancel_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_FREE_VOID
#define UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_FREE_VOID
void ffi_mob_rust_future_free_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FFI_MOB_RUST_FUTURE_COMPLETE_VOID
void ffi_mob_rust_future_complete_void(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MOB_CHECKSUM_METHOD_CLIENT_ATTACH_SIGNER
#define UNIFFI_FFIDEF_UNIFFI_MOB_CHECKSUM_METHOD_CLIENT_ATTACH_SIGNER
uint16_t uniffi_mob_checksum_method_client_attach_signer(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MOB_CHECKSUM_METHOD_CLIENT_EXECUTE_CONTRACT
#define UNIFFI_FFIDEF_UNIFFI_MOB_CHECKSUM_METHOD_CLIENT_EXECUTE_CONTRACT
uint16_t uniffi_mob_checksum_method_client_execute_contract(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MOB_CHECKSUM_METHOD_CLIENT_GET_ACCOUNT
#define UNIFFI_FFIDEF_UNIFFI_MOB_CHECKSUM_METHOD_CLIENT_GET_ACCOUNT
uint16_t uniffi_mob_checksum_method_client_get_account(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MOB_CHECKSUM_METHOD_CLIENT_GET_ALL_BALANCES
#define UNIFFI_FFIDEF_UNIFFI_MOB_CHECKSUM_METHOD_CLIENT_GET_ALL_BALANCES
uint16_t uniffi_mob_checksum_method_client_get_all_balances(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MOB_CHECKSUM_METHOD_CLIENT_GET_BALANCE
#define UNIFFI_FFIDEF_UNIFFI_MOB_CHECKSUM_METHOD_CLIENT_GET_BALANCE
uint16_t uniffi_mob_checksum_method_client_get_balance(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MOB_CHECKSUM_METHOD_CLIENT_GET_CHAIN_ID
#define UNIFFI_FFIDEF_UNIFFI_MOB_CHECKSUM_METHOD_CLIENT_GET_CHAIN_ID
uint16_t uniffi_mob_checksum_method_client_get_chain_id(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MOB_CHECKSUM_METHOD_CLIENT_GET_HEIGHT
#define UNIFFI_FFIDEF_UNIFFI_MOB_CHECKSUM_METHOD_CLIENT_GET_HEIGHT
uint16_t uniffi_mob_checksum_method_client_get_height(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MOB_CHECKSUM_METHOD_CLIENT_GET_TX
#define UNIFFI_FFIDEF_UNIFFI_MOB_CHECKSUM_METHOD_CLIENT_GET_TX
uint16_t uniffi_mob_checksum_method_client_get_tx(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MOB_CHECKSUM_METHOD_CLIENT_IS_SYNCED
#define UNIFFI_FFIDEF_UNIFFI_MOB_CHECKSUM_METHOD_CLIENT_IS_SYNCED
uint16_t uniffi_mob_checksum_method_client_is_synced(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MOB_CHECKSUM_METHOD_CLIENT_SEND
#define UNIFFI_FFIDEF_UNIFFI_MOB_CHECKSUM_METHOD_CLIENT_SEND
uint16_t uniffi_mob_checksum_method_client_send(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MOB_CHECKSUM_METHOD_SIGNER_ADDRESS
#define UNIFFI_FFIDEF_UNIFFI_MOB_CHECKSUM_METHOD_SIGNER_ADDRESS
uint16_t uniffi_mob_checksum_method_signer_address(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MOB_CHECKSUM_METHOD_SIGNER_ADDRESS_PREFIX
#define UNIFFI_FFIDEF_UNIFFI_MOB_CHECKSUM_METHOD_SIGNER_ADDRESS_PREFIX
uint16_t uniffi_mob_checksum_method_signer_address_prefix(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MOB_CHECKSUM_METHOD_SIGNER_PUBLIC_KEY_HEX
#define UNIFFI_FFIDEF_UNIFFI_MOB_CHECKSUM_METHOD_SIGNER_PUBLIC_KEY_HEX
uint16_t uniffi_mob_checksum_method_signer_public_key_hex(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MOB_CHECKSUM_METHOD_SIGNER_SIGN_BYTES
#define UNIFFI_FFIDEF_UNIFFI_MOB_CHECKSUM_METHOD_SIGNER_SIGN_BYTES
uint16_t uniffi_mob_checksum_method_signer_sign_bytes(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MOB_CHECKSUM_CONSTRUCTOR_CLIENT_NEW
#define UNIFFI_FFIDEF_UNIFFI_MOB_CHECKSUM_CONSTRUCTOR_CLIENT_NEW
uint16_t uniffi_mob_checksum_constructor_client_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MOB_CHECKSUM_CONSTRUCTOR_CLIENT_NEW_WITH_SIGNER
#define UNIFFI_FFIDEF_UNIFFI_MOB_CHECKSUM_CONSTRUCTOR_CLIENT_NEW_WITH_SIGNER
uint16_t uniffi_mob_checksum_constructor_client_new_with_signer(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_MOB_CHECKSUM_CONSTRUCTOR_SIGNER_FROM_MNEMONIC
#define UNIFFI_FFIDEF_UNIFFI_MOB_CHECKSUM_CONSTRUCTOR_SIGNER_FROM_MNEMONIC
uint16_t uniffi_mob_checksum_constructor_signer_from_mnemonic(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_MOB_UNIFFI_CONTRACT_VERSION
#define UNIFFI_FFIDEF_FFI_MOB_UNIFFI_CONTRACT_VERSION
uint32_t ffi_mob_uniffi_contract_version(void
    
);
#endif

