#!/usr/bin/env bash
#
# build-mob-android.sh
#
# Builds the mob Rust library for Android targets using the Android NDK,
# then copies the resulting .so files and UniFFI-generated Kotlin bindings
# into the Android project.
#
# Prerequisites:
#   - Android NDK installed (set ANDROID_NDK_HOME)
#   - Rust toolchain installed (rustup + cargo)
#   - Git
#
# Usage:
#   ./scripts/build-mob-android.sh
#

set -euo pipefail

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
MOB_DIR="$PROJECT_ROOT/third_party/mob"
JNI_LIBS_DIR="$PROJECT_ROOT/app/src/main/jniLibs"
BINDINGS_OUTPUT_DIR="$PROJECT_ROOT/app/src/main/java/uniffi/mob"

# Android targets and their corresponding JNI ABI folder names
# Using parallel arrays for bash 3.2 compatibility (macOS default)
TARGETS=("aarch64-linux-android" "armv7-linux-androideabi" "x86_64-linux-android")
ABIS=("arm64-v8a" "armeabi-v7a" "x86_64")

# Minimum Android API level for NDK toolchain
MIN_API_LEVEL="${MIN_API_LEVEL:-21}"

# ---------------------------------------------------------------------------
# Step 1: Check for ANDROID_NDK_HOME
# ---------------------------------------------------------------------------

echo "==> Checking environment..."

if [ -z "${ANDROID_NDK_HOME:-}" ]; then
    echo "ERROR: ANDROID_NDK_HOME is not set."
    echo ""
    echo "Set it to the path of your Android NDK installation, e.g.:"
    echo "  export ANDROID_NDK_HOME=\$HOME/Library/Android/sdk/ndk/27.0.12077973"
    echo ""
    echo "You can find installed NDKs under \$ANDROID_HOME/ndk/ or install one"
    echo "via Android Studio > SDK Manager > SDK Tools > NDK (Side by side)."
    exit 1
fi

if [ ! -d "$ANDROID_NDK_HOME" ]; then
    echo "ERROR: ANDROID_NDK_HOME points to a directory that does not exist:"
    echo "  $ANDROID_NDK_HOME"
    exit 1
fi

echo "    ANDROID_NDK_HOME = $ANDROID_NDK_HOME"

# Locate the NDK toolchain. NDK r23+ uses a single unified toolchain.
TOOLCHAIN="$ANDROID_NDK_HOME/toolchains/llvm/prebuilt"
HOST_TAG=""
for candidate in linux-x86_64 darwin-x86_64 darwin-arm64 windows-x86_64; do
    if [ -d "$TOOLCHAIN/$candidate" ]; then
        HOST_TAG="$candidate"
        break
    fi
done

if [ -z "$HOST_TAG" ]; then
    echo "ERROR: Could not detect NDK host toolchain under $TOOLCHAIN"
    exit 1
fi

TOOLCHAIN_BIN="$TOOLCHAIN/$HOST_TAG/bin"
echo "    NDK toolchain   = $TOOLCHAIN_BIN"

# Verify required tools
command -v rustup >/dev/null 2>&1 || { echo "ERROR: rustup not found. Install Rust: https://rustup.rs"; exit 1; }
command -v cargo  >/dev/null 2>&1 || { echo "ERROR: cargo not found. Install Rust: https://rustup.rs"; exit 1; }
command -v git    >/dev/null 2>&1 || { echo "ERROR: git not found."; exit 1; }

echo "    Rust toolchain   = $(rustc --version)"
echo ""

# ---------------------------------------------------------------------------
# Step 2: Clone mob repo if not already present
# ---------------------------------------------------------------------------

echo "==> Checking for mob source..."

if [ -d "$MOB_DIR" ]; then
    echo "    mob repo already exists at $MOB_DIR"
    echo "    Pulling latest changes..."
    git -C "$MOB_DIR" pull --ff-only || echo "    (pull skipped — may be on a pinned commit)"
else
    echo "    Cloning mob repo..."
    mkdir -p "$(dirname "$MOB_DIR")"
    git clone https://github.com/burnt-labs/mob "$MOB_DIR"
fi

echo ""

# ---------------------------------------------------------------------------
# Step 3: Install Rust Android targets
# ---------------------------------------------------------------------------

echo "==> Installing Rust Android targets..."

for TARGET in "${TARGETS[@]}"; do
    echo "    Adding target: $TARGET"
    rustup target add "$TARGET"
done

echo ""

# ---------------------------------------------------------------------------
# Step 4: Configure Cargo for Android NDK cross-compilation
# ---------------------------------------------------------------------------

echo "==> Configuring Cargo for Android NDK cross-compilation..."

# We create a .cargo/config.toml inside the mob repo so it only affects
# builds within that directory, keeping the user's global config clean.
CARGO_CONFIG_DIR="$MOB_DIR/.cargo"
CARGO_CONFIG_FILE="$CARGO_CONFIG_DIR/config.toml"

mkdir -p "$CARGO_CONFIG_DIR"

# The NDK provides target-specific clang wrappers that handle sysroot and
# linking automatically. We point each Rust target at the appropriate one.
cat > "$CARGO_CONFIG_FILE" <<TOML
# Auto-generated by build-mob-android.sh — do not edit manually.
# Configures linkers for Android NDK cross-compilation.

[target.aarch64-linux-android]
linker = "${TOOLCHAIN_BIN}/aarch64-linux-android${MIN_API_LEVEL}-clang"

[target.armv7-linux-androideabi]
linker = "${TOOLCHAIN_BIN}/armv7a-linux-androideabi${MIN_API_LEVEL}-clang"

[target.x86_64-linux-android]
linker = "${TOOLCHAIN_BIN}/x86_64-linux-android${MIN_API_LEVEL}-clang"
TOML

echo "    Wrote $CARGO_CONFIG_FILE"
echo ""

# ---------------------------------------------------------------------------
# Step 5: Build mob for each Android target
# ---------------------------------------------------------------------------

echo "==> Building mob for Android targets..."

# Set AR for each target (NDK's llvm-ar works for all targets)
export AR="${TOOLCHAIN_BIN}/llvm-ar"

# Some crates need CC set for the C compiler
for i in "${!TARGETS[@]}"; do
    TARGET="${TARGETS[$i]}"
    ABI="${ABIS[$i]}"
    echo ""
    echo "--- Building for $TARGET ($ABI) ---"

    # Set the CC environment variable for the specific target
    case "$TARGET" in
        aarch64-linux-android)
            export CC_aarch64_linux_android="${TOOLCHAIN_BIN}/aarch64-linux-android${MIN_API_LEVEL}-clang"
            ;;
        armv7-linux-androideabi)
            export CC_armv7_linux_androideabi="${TOOLCHAIN_BIN}/armv7a-linux-androideabi${MIN_API_LEVEL}-clang"
            ;;
        x86_64-linux-android)
            export CC_x86_64_linux_android="${TOOLCHAIN_BIN}/x86_64-linux-android${MIN_API_LEVEL}-clang"
            ;;
    esac

    # Build from MOB_DIR so cargo picks up .cargo/config.toml for NDK linkers
    (cd "$MOB_DIR" && cargo build --release --target "$TARGET")

    echo "    Build complete for $TARGET"
done

echo ""

# ---------------------------------------------------------------------------
# Step 6: Copy .so files to jniLibs
# ---------------------------------------------------------------------------

echo "==> Copying .so files to jniLibs..."

for i in "${!TARGETS[@]}"; do
    TARGET="${TARGETS[$i]}"
    ABI="${ABIS[$i]}"
    SRC="$MOB_DIR/target/$TARGET/release/libmob.so"
    DEST_DIR="$JNI_LIBS_DIR/$ABI"
    DEST="$DEST_DIR/libmob.so"

    mkdir -p "$DEST_DIR"

    if [ -f "$SRC" ]; then
        cp "$SRC" "$DEST"
        echo "    $ABI: $(du -h "$DEST" | cut -f1) -> $DEST"
    else
        echo "    WARNING: $SRC not found. The crate may produce a different lib name."
        echo "    Checking for any .so files in $MOB_DIR/target/$TARGET/release/:"
        find "$MOB_DIR/target/$TARGET/release/" -maxdepth 1 -name "*.so" 2>/dev/null || echo "      (none found)"
    fi
done

echo ""

# ---------------------------------------------------------------------------
# Step 7: Copy UniFFI-generated Kotlin bindings
# ---------------------------------------------------------------------------

echo "==> Copying UniFFI Kotlin bindings..."

# UniFFI generates Kotlin bindings during the build. The typical output
# location depends on how the mob crate is configured — check common paths.
UNIFFI_BINDINGS=""
for CANDIDATE in \
    "$MOB_DIR/target/release/build/"*"/out/uniffi/mob/mob.kt" \
    "$MOB_DIR/target/aarch64-linux-android/release/build/"*"/out/uniffi/mob/mob.kt" \
    "$MOB_DIR/bindings/kotlin/mob/mob.kt" \
    "$MOB_DIR/src/mob.udl"; do

    # Use the first .kt file we find
    FOUND=$(find "$(dirname "$CANDIDATE")" -name "mob.kt" 2>/dev/null | head -1 || true)
    if [ -n "$FOUND" ] && [ -f "$FOUND" ]; then
        UNIFFI_BINDINGS="$FOUND"
        break
    fi
done

if [ -n "$UNIFFI_BINDINGS" ]; then
    mkdir -p "$BINDINGS_OUTPUT_DIR"
    cp "$UNIFFI_BINDINGS" "$BINDINGS_OUTPUT_DIR/mob.kt"
    echo "    Copied $UNIFFI_BINDINGS -> $BINDINGS_OUTPUT_DIR/mob.kt"
else
    echo "    WARNING: Could not find UniFFI-generated mob.kt bindings."
    echo "    You may need to generate them manually:"
    echo "      cargo run --bin uniffi-bindgen generate --library target/release/libmob.so --language kotlin --out-dir bindings/"
    echo "    Then copy the generated .kt file to: $BINDINGS_OUTPUT_DIR/"
fi

echo ""

# ---------------------------------------------------------------------------
# Done
# ---------------------------------------------------------------------------

echo "========================================="
echo "  Build complete!"
echo "========================================="
echo ""
echo "JNI libs:  $JNI_LIBS_DIR/"
echo "Bindings:  $BINDINGS_OUTPUT_DIR/"
echo ""
echo "Next steps:"
echo "  1. Verify .so files exist in each jniLibs ABI folder"
echo "  2. Ensure mob.kt bindings are in $BINDINGS_OUTPUT_DIR/"
echo "  3. Build the Android project: ./gradlew assembleDebug"
echo ""
